In [2]:
import numpy as np

In [28]:
A= np.array(np.mat("111 211 311; 121 221 321; 131 231 331"))
B= np.array(np.mat("112 212 312; 122 222 322; 132 232 332"))
C= np.array(np.mat("113 213 313; 123 223 323; 133 233 333"))
Tensor_komp = np.array([A,B,C])
Tensor_komp

array([[[111, 211, 311],
        [121, 221, 321],
        [131, 231, 331]],

       [[112, 212, 312],
        [122, 222, 322],
        [132, 232, 332]],

       [[113, 213, 313],
        [123, 223, 323],
        [133, 233, 333]]])

In [16]:
Epsilon_Tensor = Tensor_komp

In [72]:
Tensor_komp[0][1][1]

221

In [67]:
def check_permutation(A,B):
    """
    A = Vergleichs Permutation
    B = geprüfte Permutation
    """
    b = len(B)
    a = np.divmod(A, 10) # k = a[1] 
    aa = np.divmod(a[0], 10)# j = aa[1] und i = aa[0]
    
    #b = np.divmod(B, 10) # k = b[1] 
    #bb = np.divmod(b[0], 10) #j = bb[1] und i = bb[0]
    
    if ((B[0] == B[1]) or (B[1] == B[2]) or (B[0] == B[2])):
        return 0
    elif ((B[2] == a[1]) or (B[1] == aa[1]) or (B[0] == aa[0])):
        return -1
    else:
        return 1

In [70]:
a = check_permutation(123, [3, 1, 2])
print(a)

1


In [79]:
ijk = 123

for k in enumerate(Tensor_komp, 1):
    for j in enumerate(k[1], 1):
        for i in enumerate(j[1], 1):
            komp = np.array([i[0], j[0], k[0]])
            Epsilon_Tensor[k[0]-1][j[0]-1][i[0]-1] = check_permutation(ijk, komp)
Epsilon_Tensor
            
            

array([[[ 0,  0,  0],
        [ 0,  0, -1],
        [ 0,  1,  0]],

       [[ 0,  0,  1],
        [ 0,  0,  0],
        [-1,  0,  0]],

       [[ 0, -1,  0],
        [-1,  0,  0],
        [ 0,  0,  0]]])

In [56]:
A = 123
a = np.divmod(A, 10)
aa = np.divmod(a[0], 10)
aa

(1, 2)

In [80]:
x = np.dot(Epsilon_Tensor[0], Epsilon_Tensor[1])
x

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [ ]:
def tensor_cross(a,b):
    e1 = 